Conti2D: DWC_s2p
DWC_p2p
DWC_p2p_LandweberIter
DWC_s2p
DWC_s2p_LandweberIter
GetGij
Getkernel_p2p_new
Getkernel_p2p_new
Getkernel_p2s_new
GetPmnij
UWC_Gij
UWC_Gij
UWC_p2p
UWC_p2p_f
UWC_p2p_f
UWC_p2s
DWC_s2p()
void DWC_s2p (string inputfilename, string outputfilename, string topoFile, double height2, int extNum, double DWC_parameter, int DWC_method, int num_thread, bool isProgress, string filename_exact)
Downward continuation: uneven surface to plane(space domain)
Parameters
inputfilename Grid file of the observation field.
outputfilename
topoFile Topography grid file of the observation field.
height2 Elevation of the continuation plane.
extNum
DWC_parameter
DWC_method
num_thread
isProgress
filename_exact
Definition at line 605 of file Conti2D.cpp.
References GrdHead::bounds, COLOR_DEFALUT, GrdHead::cols, DWC_LANDWEBER, DWC_s2p_LandweberIter(), Getkernel_p2s_new(), GREEN, Path_GetExtName(), Path_GetFileName(), ReadGrd(), RED, GrdHead::rows, SaveGrd(), SaveGrd2netCDF(), SaveGrd2VTK(), SaveGrd2VTK_topo(), and SaveGrd2xyz().
Referenced by main().