Conti2D: Getkernel_p2s_new
DWC_p2p
DWC_p2p_LandweberIter
DWC_s2p
DWC_s2p_LandweberIter
GetGij
Getkernel_p2p_new
Getkernel_p2p_new
Getkernel_p2s_new
GetPmnij
UWC_Gij
UWC_Gij
UWC_p2p
UWC_p2p_f
UWC_p2p_f
UWC_p2s
Getkernel_p2s_new()
int Getkernel_p2s_new (GrdHead grdhead, double h1, double * topo2, double ** kernel, int num_thread)
Get complete kernel matrix for upward continuation from plane to surface.
Parameters
grdhead
h1 Elevation of the observation field.
topo2 Topography of the continuation points(or calculation points)
kernel Save kernel matrix to a 2D array
num_thread How many threads used to calculate
Returns
int
Definition at line 121 of file Conti2D.cpp.
References GrdHead::bounds, COLOR_BAR_BLUE, GrdHead::cols, GetPmnij(), GrdHead::rows, and MultiProgressBar::Update().
Referenced by DWC_s2p(), and UWC_p2s().