Conti2D: UWC_p2p
BLUE
CLEAR
COLOR_DEFALUT
DWC_CGLS
DWC_INTEGRALITERATION
DWC_LANDWEBER
DWC_p2p
DWC_p2p_CGLS
DWC_p2p_f
DWC_p2p_ItegrationIter
DWC_p2p_LandweberIter
DWC_s2p
DWC_s2p_CGLS
DWC_s2p_ItegrationIter
DWC_s2p_LandweberIter
DWC_s2p_Tikhonov
DWC_TIKHONOV
DWC_Tikhonov_old
DWC_u2p
ERR
ERRCODE
ERROR_COUT
ERROR_COUT
GetGij
GetKernalMatrix
GetKernalMatrix_new
Getkernel_p2p
Getkernel_p2p_new
Getkernel_p2p_new
Getkernel_p2s_new
Getkernel_u2p
Getkernel_u2p_new
GetPmnij
GREEN
helpINFO
HIDE_CURSOR
HIGHT_LIGHT
MOVEDOWN
MOVELEFT
MOVERIGHT
MOVETO
MOVEUP
MOVEUP
Norm2
Norm2_Gradient
OutputErrorinfo
OutputWarninginfo
Path_GetBaseName
Path_GetExtName
Path_GetFileName
Path_GetPath
PI
PURPLE
ReadGrd
RED
RESET_CURSOR
SaveGrd
SaveGrd2netCDF
SaveGrd2VTK
SaveGrd2VTK_topo
SaveGrd2xyz
SHOW_CURSOR
StartText
StartText_artASCII
Text_Axis
UN_HIGHT_LIGHT
UWC
UWC_G_CGLS_Tik
UWC_Gij
UWC_Gij
UWC_Gji
UWC_Gji
UWC_p2p
UWC_p2p_f
UWC_p2p_f
UWC_p2s
WARN_COUT
YELLOW
UWC_p2p()
void UWC_p2p (string inputfilename, string outputfilename, double height1, double height2, int extNum, int num_thread, bool isProgress, bool useOldKernel, string filename_exact)
Definition at line 421 of file Conti2D.cpp.
References COLOR_DEFALUT, GrdHead::cols, Getkernel_p2p_new(), GREEN, Path_GetExtName(), Path_GetFileName(), ReadGrd(), RED, GrdHead::rows, SaveGrd(), SaveGrd2netCDF(), SaveGrd2VTK(), SaveGrd2xyz(), and UWC_Gij().
Referenced by main().