Conti2D: DWC_s2p_LandweberIter
DWC_p2p
DWC_p2p_LandweberIter
DWC_s2p
DWC_s2p_LandweberIter
GetGij
Getkernel_p2p_new
Getkernel_p2p_new
Getkernel_p2s_new
GetPmnij
UWC_Gij
UWC_Gij
UWC_p2p
UWC_p2p_f
UWC_p2p_f
UWC_p2s
DWC_s2p_LandweberIter()
void DWC_s2p_LandweberIter (double ** G, double * x, double * b, GrdHead grdhead, int extNum, int num_thread, string outputfile, double iter_number, double * ExactSolution)
Calculate downward continuation of potential field from surface to a plane.
Parameters
G The complete kernel matrix.
x Result
b Observation field data.
grdhead
extNum
num_thread
outputfile
iter_number
ExactSolution
Definition at line 916 of file Conti2D.cpp.
References COLOR_DEFALUT, GrdHead::cols, GREEN, Norm2(), Norm2_Gradient(), Path_GetFileName(), RED, GrdHead::rows, SaveGrd2VTK(), MultiProgressBar::Update(), and UWC_Gij().
Referenced by DWC_p2p(), and DWC_s2p().