Conti2D: SaveGrd2netCDF
Norm2
Norm2_Gradient
Path_GetBaseName
Path_GetExtName
Path_GetFileName
Path_GetPath
ReadGrd
SaveGrd
SaveGrd2netCDF
SaveGrd2VTK
SaveGrd2VTK_topo
SaveGrd2xyz
SaveGrd2netCDF()
bool SaveGrd2netCDF (string filename, GrdHead grdhead, double * data, int extNum, bool isInfo)
Save Grd data as netCDF format.
Save grid data to netCDF format.
see https://www.unidata.ucar.edu/software/netcdf/ for details.
Parameters
filename
grdhead
data
extNum
isInfo
Returns
true
false
Definition at line 197 of file stdfunc.cpp.
References GrdHead::bounds, GrdHead::cols, ERR, and GrdHead::rows.
Referenced by DWC_s2p(), UWC_p2p(), UWC_p2p_f(), and UWC_p2s().